version: "3.8"

services:
  bot_db:
    image: postgres:latest
    container_name: bot_db
    command: -p 5434
    ports:
      - "5433:5434"
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  bot:
    build: .
    command: >
      /bin/sh -c "alembic upgrade head && python main.py"
    restart: always
    volumes:
      - ./:/bot
    ports:
      - "8003:8000"
    env_file:
      - ./.env
    depends_on:
      - bot_db
    networks:
      - my_shared_network


networks:
  my_shared_network:
    external: true