version: "3.8"

services:
  bot_db:
    image: postgres:latest
    container_name: bot_db
    command: -p 5434
    ports:
      - "5433:5434"
    env_file:
      - ./.env.dev.db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  bot:
    build: .
    command: >
      /bin/sh -c "alembic upgrade head && python main.py"
    restart: always
    volumes:
      - ./:/bot
    env_file:
      - ./.env.dev
    depends_on:
      - bot_db
