"""add uwords uid

Revision ID: 5196f68b12f0
Revises: 
Create Date: 2024-08-24 17:49:18.681216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5196f68b12f0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_user_id", sa.Integer(), nullable=True),
        sa.Column("uwords_uid", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_user_id"),
        sa.UniqueConstraint("uwords_uid"),
    )
    op.create_index(op.f("ix_User_id"), "User", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_User_id"), table_name="User")
    op.drop_table("User")
    # ### end Alembic commands ###
