"""add state

Revision ID: d7efd958b58e
Revises: 5196f68b12f0
Create Date: 2024-08-25 17:33:56.206165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7efd958b58e"
down_revision: Union[str, None] = "5196f68b12f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("state", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "state")
    # ### end Alembic commands ###
